name: build openwrt image

# only triggerd Manually
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: install dependencies
        run: |
          sudo apt-get -y install build-essential ccache ecj fastjar file g++ gawk \
          gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
          python-distutils-extra python3-setuptools python3-dev rsync subversion \
          swig time xsltproc zlib1g-dev

      - name: clone & checkout repo
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd ./openwrt
          #git checkout v21.02.3
          git checkout v22.03.2

      - name: update all feeds
        run: |
          cd ./openwrt
          ./scripts/feeds update -a

      - name: install all feeds
        run: |
          cd ./openwrt
          ./scripts/feeds install -a

      - name: make configuration
        run: cp .config ./openwrt

      - name: download packages
        run: |
          cd ./openwrt
          make download

      - name: build firmware
        run: |
          cd ./openwrt
          make V=99
          
      - name: download upload tool
        run: |
          mkdir tools
          cd tools
          curl -fsSL https://github.com/Mikubill/transfer/releases/download/v0.4.17/transfer_0.4.17_linux_amd64.tar.gz -o transfer.tar.gz
          tar -xzf transfer.tar.gz
          
      - name: upload firmware to wetransfer
        run: |
          cd tools
          ./transfer wet -s --no-progress ../openwrt/bin/targets/bcm27xx/bcm2708/openwrt-bcm27xx-bcm2708-rpi-ext4-factory.img.gz

#          if [-d "./openwrt/bin/targets/bcm27xx/bcm2708"]; then
#            cd ./openwrt/bin/targets/bcm27xx/bcm2708
#            ls
#          fi
