name: test tools

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-20.04
    
    steps:
      - name: checkout
        uses: actions/checkout@main
      
      - name: download
        run: |
          mkdir tools
          cd tools
          curl -fsSL https://github.com/Mikubill/transfer/releases/download/v0.4.17/transfer_0.4.17_linux_amd64.tar.gz -o transfer.tar.gz
          tar -xzf transfer.tar.gz
          ls -al
